del fmr\*.map
del fmr\bin\*.exe
del fmr\estruct.h
del fmr\obj\*.obj
del freebsd\emacs
del freebsd\estruct.h
del freebsd\obj\*.o
del hp150\*.map
del hp150\bin\*.exe
del hp150\estruct.h
del hp150\execpr.crf
del hp150\execpr.lst
del hp150\obj\*.obj
del i55\*.map
del i55\bin\*.exe
del i55\estruct.h
del i55\execpr.crf
del i55\execpr.lst
del i55\obj\*.obj
del mswin\bcpp\*.map
del mswin\bcpp\bin\*.exe
del mswin\bcpp\estruct.h
del mswin\bcpp\obj\*.obj
del mswin\msc\*.map
del mswin\msc\bin\*.exe
del mswin\msc\estruct.h
del mswin\msc\obj\*.obj
del nec\*.map
del nec\bin\*.exe
del nec\estruct.h
del nec\obj\*.obj
del nt\*.map
del nt\bin\*.exe
del nt\estruct.h
del nt\obj\*.obj
del os2\*.map
del os2\bin\*.exe
del os2\estruct.h
del os2\obj\*.obj
del pcdos\ansi\*.map
del pcdos\ansi\bin\*.exe
del pcdos\ansi\estruct.h
del pcdos\ansi\execpr.crf
del pcdos\ansi\execpr.lst
del pcdos\ansi\obj\*.obj
del pcdos\dos16m\*.map
del pcdos\dos16m\bin\*.dbg
del pcdos\dos16m\bin\*.exe
del pcdos\dos16m\bin\*.exp
del pcdos\dos16m\estruct.h
del pcdos\dos16m\obj\*.obj
del pcdos\ic\emacs.exe
del pcdos\ic\estruct.h
del pcdos\m6\*.map
del pcdos\m6\bin\*.exe
del pcdos\m6\estruct.h
del pcdos\m6\execpr.crf
del pcdos\m6\execpr.lst
del pcdos\m6\obj\*.obj
del pcdos\m7\*.map
del pcdos\m7\bin\*.exe
del pcdos\m7\estruct.h
del pcdos\m7\execpr.crf
del pcdos\m7\execpr.lst
del pcdos\m7\obj\*.obj
del pcdos\msc\*.map
del pcdos\msc\bin\*.exe
del pcdos\msc\estruct.h
del pcdos\msc\execpr.crf
del pcdos\msc\execpr.lst
del pcdos\msc\obj\*.obj
del pcdos\turbo\*.map
del pcdos\turbo\bin\*.exe
del pcdos\turbo\estruct.h
del pcdos\turbo\execpr.crf
del pcdos\turbo\execpr.lst
del pcdos\turbo\obj\*.obj
del sun4\cc\bin\emacs
del sun4\cc\estruct.h
del sun4\cc\obj\*.o
del sun4\gcc\bin\emacs
del sun4\gcc\estruct.h
del sun4\gcc\obj\*.o
