/*	NEDERLANDS.H:	Dutch language text strings for
                        MicroEMACS 3.12

			Translated by Paul De Bra
			debra@research.att.com          
			(C)opyright 1993 by Daniel Lawrence
*/

#define	TEXT1	"[Opstarten nieuwe CLI]"
#define	TEXT2	"[Kan niet schrijven in filter file]"
#define	TEXT3	"[Uitvoering mislukt]"
#define	TEXT4	"Shell variabele TERM niet gedefinieerd!"
#define	TEXT5	"Terminal type is geen 'vt100'!"
#define	TEXT6	"\r\n\n[Einde]"
#define	TEXT7	"Lijn om naar te springen: "
#define	TEXT8	"[Onderbroken]"
#define	TEXT9	"[Markering %d gezet]"
#define	TEXT10	"[Markering %d verwijderd]"
#define	TEXT11	"Geen markering %d in dit venster"
#define	TEXT12	"[Hulp file is niet aanwezig]"
#define	TEXT13	": beschrijf-toets "
#define	TEXT14	"Niet gebonden"
#define	TEXT15	": bind-aan-toets "
#define	TEXT16	"[Onbestaande functie]"
#define	TEXT17	"Verbindings-tabel VOL!"
#define	TEXT18	": verwijder verbinding-toets "
#define	TEXT19	"[Toets niet gebonden]"
#define	TEXT20	"Beschrijf woord: "
#define	TEXT21	"Verbindings lijst"
#define	TEXT22	"Kan verbindings-lijst niet tonen"
#define	TEXT23	"[Opbouwen van verbindings-lijst]"
#define	TEXT24	"Gebruik buffer"
#define	TEXT25	"Gebruik buffer: "
#define	TEXT26	"Vernietig buffer"
#define	TEXT27	"Pop buffer"
#define	TEXT28	"Buffer wordt nog getoond"
#define	TEXT29	"Verander buffer-naam in: "
#define	TEXT30	"ACTN   Modus   Grootte Buffer          File"
/*   ^^^The underlining will not match exactly for this line, but it's close*/
#define	TEXT31	"         Globale Modi"
#define	TEXT32	"Vergeet Veranderingen"
#define	TEXT33	"Encryptie Sleutel: "
#define	TEXT34	"File: "
#define	TEXT35	"een andere gebruiker"
/*The UNIX terms should stay the same in the next few entryies*/
#define	TEXT36	"LOCK FOUT -- "
#define	TEXT37	"test naar het bestaan van %s\n"
#define	TEXT38	"creeren van directory %s\n"
#define	TEXT39	"creeren van %s\n"
#define	TEXT40	"kon lock-file niet creeren"
#define	TEXT41	"proces nummer is %ld\n"
#define	TEXT42	"lezen van lock-file %s\n"
#define	TEXT43	"kon lock-file niet lezen"
#define	TEXT44	"process nummer in %s is %ld\n"
#define	TEXT45	"signaal gestuurd naar proces %ld\n"
#define	TEXT46	"proces bestaat"
#define	TEXT47	"signaleren mislukt"
#define	TEXT48	"signaleren gelukt; proces bestaat"
#define	TEXT49	"poging om %s te verwijderen\n"
#define	TEXT50	"kon lock-file niet verwijderen"
#define	TEXT51	"Variabele om te zetten: "
#define	TEXT52	"%%Er bestaat geen variabele '%s'"
#define	TEXT53	"Waarde: "
#define	TEXT54	"[Macro onderbroken]"
#define	TEXT55	"Variabele om te tonen: "
#define	TEXT56	"Lijst van variabelen"
#define	TEXT57	"Kan lijst van variabelen niet tonen"
#define	TEXT58	"[Opbouwen lijst van variabelen]"
#define	TEXT59	"[Rechter marge is %d]"
#define	TEXT60	"Lijn %D/%D Kolom %d/%d Kar. %D/%D (%d%%) Kar. = 0x%x"
#define	TEXT61	"<NOT USED>"
#define	TEXT62	"Globale modus om "
#define	TEXT63	"Modus om "
#define	TEXT64	"toe te voegen: "
#define	TEXT65	"te verwijderen: "
#define	TEXT66	"onbestaande modus!"
#define	TEXT67	"Te schrijven bericht: "
#define	TEXT68	"In te voegen woord: "
#define	TEXT69	"Te overschrijven woord: "
#define	TEXT70	"[geselecteerd stuk gecopieerd]"
#define	TEXT71	"%%Deze buffer is al vernauwd"
#define	TEXT72	"%%Moet minstens 1 hele lijn vernauwen"
#define	TEXT73	"[Buffer is vernauwd]"
#define	TEXT74	"%%Deze buffer is niet vernauwd"
#define	TEXT75	"[Buffer is verbreed]"
#define	TEXT76	"Geen markering gezet in dit venster"
#define	TEXT77	"Interne Fout: markering verloren"
#define	TEXT78	"Zoek"
#define	TEXT79	"Niet gevonden"
#define	TEXT80	"Geen patroon gezet"
#define	TEXT81	"Zoek achterwaards "
#define	TEXT82	"Beschouwen van %d met sprong %d"
#define	TEXT83	"Het andere geval is %d"
#define	TEXT84	"Vervang"
#define	TEXT85	"Vervang voorwaardelijk"
#define	TEXT86	"door "
#define	TEXT87	"Vervangen van '"
#define	TEXT88	"' door '"
#define	TEXT89	"Onderbroken!"
#define	TEXT90	"(Y)Ja, (N)ee, (!)Doe rest, (U)Ongedaan, (^G)Breek af, (.)Stop, (?)Help: "
#define	TEXT91	"Leeg woord vervangen en gestopt."
#define	TEXT92	"%d vervangingen"
#define	TEXT93	"%%FOUT tijdens wegvegen"
#define	TEXT94	"%%Geen geheugen meer"
#define	TEXT95	"%%mceq: wat is %d?"
#define	TEXT96	"%%Geen karakters in karakter klasse"
#define	TEXT97	"%%Karakter klasse niet beeindigd"
#define	TEXT98	"Geen rechter marge gezet"
#define	TEXT99	"[GEEN GEHEUGEN MEER]"
#define	TEXT100	"Woorden %D Karakters %D Lijnen %d Gem kars/woord %f"
#define	TEXT101	"[Kan niet zoeken en springen tegelijkertijd!]"
#define	TEXT102	"[Zinloos sprong argument]"
#define	TEXT103	"[Bewaren %s]"
#define	TEXT104	"Er zijn veranderde buffers. Toch stoppen"
#define	TEXT105	"%%Macro is al aktief"
#define	TEXT106	"[Start macro]"
#define	TEXT107	"%%Macro is niet aktief"
#define	TEXT108	"[Einde macro]"
#define	TEXT109	"[Toets niet toegelaten in BEKIJK modus]"
#define	TEXT110	"[Dit commando is GERESERVEERD]"
#define	TEXT111	"Geen macro opgegeven"
#define	TEXT112	"Macro nummer bestaat niet"
#define	TEXT113	"Kan macro niet creeren"
#define	TEXT114	"Procedure naam: "
#define	TEXT115	"Uit te voeren procedure: "
#define	TEXT116	"Onbestaande procedure"
#define	TEXT117	"Uit te voeren buffer: "
#define	TEXT118	"Onbestaande buffer"
#define	TEXT119	"%%Geen geheugen meer tijdens opzoeking"
#define	TEXT120	"%%!BREAK buiten !WHILE lus"
#define	TEXT121	"%%!ENDWHILE zonder voorafgaande !WHILE"
#define	TEXT122	"%%!WHILE zonder overeenkomstige !ENDWHILE"
#define	TEXT123	"%%Geen geheugen meer tijdens uitvoering van macro"
#define	TEXT124	"%%Onbekende Verwijzing"
#define	TEXT125	"Geen geheugen meer tijdens opslaan van macro"
#define	TEXT126	"%%Interne While lus fout"
#define	TEXT127	"%%Onbestaand label"
#define	TEXT128	"(e)val, (c/x)ommando, (t)Volg, (^G)breek af, <SP>doe, <META> stop debug"
#define	TEXT129	"Uit te voeren file: "
#define	TEXT130	"Macro niet gedefinieerd"
#define	TEXT131	"Lees file"
#define	TEXT132	"In te voegen file"
#define	TEXT133	"Vind file"
#define	TEXT134	"Bekijk file"
#define	TEXT135	"[Oude buffer]"
#define	TEXT136	"Buffer naam: "
#define	TEXT137	"Kan buffer niet creeren"
#define	TEXT138	"[Nieuwe file]"
#define	TEXT139	"[Lezen van file]"
#define	TEXT140	"Lees "
#define	TEXT141	"I/O FOUT, "
#define	TEXT142	"GEEN GEHEUGEN MEER, "
#define	TEXT143	" lijn"
#define	TEXT144	"Schrijf file: "
#define	TEXT145	"Geen filenaam"
#define	TEXT146	"Verkort file..bewaren"
#define	TEXT147	"Vernauwde Buffer..bewaren"
#define	TEXT148	"[Bewaren...]"
#define	TEXT149	"[Bewaard als "
#define	TEXT150	", bewaard als "
#define	TEXT151	"Naam: "
#define	TEXT152	"[File bestaat niet]"
#define	TEXT153	"[Invoegen file]"
#define	TEXT154	"Ingevoegd "
#define	TEXT155	"Kan file niet bewaren"
#define	TEXT156	"Kan file niet afsluiten"
#define	TEXT157	"Bewaar I/O fout"
#define	TEXT158	"File lees-fout"
#define	TEXT159	"%Heb nummer van functietoets nodig"
#define	TEXT160	"%Functietoets met dit nummer bestaat niet"
#define	TEXT161	"Label inhoud: "
#define	TEXT162	" [y(ja)/n]? "
#define	TEXT163	"geen default"
#define	TEXT164	"[opzoeken mislukt]"
#define	TEXT165	"Zoek Incrementeel: "
#define	TEXT166	"? Te zoeken woord te lang"
#define	TEXT167	"? commando te lang"
#define	TEXT168	"%%Kan woord niet invoegen"
#define	TEXT169	"Ingevoegd"
#define	TEXT170	"interne fout: linsert"
#define	TEXT171	"Vervangen"
#define	TEXT172	"%%Geen geheugen meer tijdens overschrijven"
#define	TEXT173	"LOCK FOUT: Lock tabel vol"
#define	TEXT174	"Kan geen lock zetten, geen geheugen meer"
#define	TEXT175	"LOCK"
#define	TEXT176	"File in gebruik door "
#define	TEXT177	", toch proberen?"
#define	TEXT178	"[kan foutenboodschap van systeem niet ontvangen]"
#define	TEXT179	"  Over MicroEmacs"
#define	TEXT180	"%%Onbestaande resolutie"
#define	TEXT181	"%%Onmogelijke Resolutie voor dit scherm"
#define	TEXT182	"Omgevings-variable TERM not defined!"
#define	TEXT183	"Onbekend terminal type %s!"
#define	TEXT184	"termcap definitie onvolledig (lijnen)"
#define	TEXT185	"Termcap definitie onvolledig (kolommen)"
#define	TEXT186	"Onvolledige termcap definitie\n"
#define	TEXT187	"Beschrijving van terminal is te lang!\n"
#define	TEXT188	"[Einde]"
#define	TEXT189	"Kan geen definitie voor dit terminal type.\n"
#define	TEXT190	"Controleer terminal type met \"SHOW TERMINAL\" of\n"
#define	TEXT191	"probeer het te zetten met \"SET TERMINAL/INQUIRE\"\n"
#define	TEXT192	"Deze terminal is niet krachtig genoeg om MicroEMACS\n"
#define	TEXT193	"te gebruiken. Probeer een andere terminal of controleer\n"
#define	TEXT194	"het type met \"SHOW TERMINAL\".\n"
#define	TEXT195	"Kan communicatie met terminal niet openen.\n"
#define	TEXT196	"Kan instelling van de terminal niet opvragen.\n"
#define	TEXT197	"Kan instelling van de terminal niet veranderen.\n"
#define	TEXT198	"I/O fout (%d,%d)\n"
#define	TEXT199	"[Start DCL]\r\n"
#define	TEXT200	"[Oproepen DCL]\r\n"
#define	TEXT201	"[Nog niet beschikbaar voor VMS]"
#define	TEXT202	"Terminal is geen 'vt52'of 'z19' !"
#define	TEXT203	"Venster met dit nummer bestaat niet"
#define	TEXT204	"Kan dit venster niet verwijderen"
#define	TEXT205	"Kan een venster met %d lijnen niet opsplitsen"
#define	TEXT206	"Er is maar 1 venster"
#define	TEXT207	"Onmogelijke verandering"
#define	TEXT208	"[Dat venster bestaat niet]"
#define	TEXT209	"%%Deze scherm grootte wordt niet ondersteund"
#define	TEXT210	"%%Deze scherm breedte wordt niet ondersteund"
#define	TEXT211	"Lijst van functies"
#define	TEXT212	"Kan lijst van functie niet tonen"
#define	TEXT213	"[Opbouwen lijst van functie]"
#define	TEXT214 "%%File niet bekend als %s"
#define	TEXT215	": macro-aan-toets "
#define TEXT216 "Kan directories niet lezen/schrijven"
#define TEXT217 "[Nog niet beschikbaar onder AOS/VS]"
#define	TEXT218	"Toevoegen file: "
#define TEXT219 "%%Macro Fout"
#define	TEXT220	"Lijn %D/%D Kolom %d/%d Kar. %D/%D (%d%%) Kar. = 0x%x%x"
#define TEXT221 "Te veel groepen"
#define TEXT222 "Groep niet beeindigd"
#define	TEXT223 "%%Kolom start buiten toegelaten waarde"
#define	TEXT224 "%%Rij start buiten toegelaten waarde"
#define	TEXT225 "[Gegaan naar scherm %s]"
#define	TEXT226	"%%Kan executing buffer niet verwijderen"
#define	TEXT227 "\n--- Druk op een toets om verder te gaan ---"
#define TEXT228 "[Kill ring gewist]"
#define TEXT229 " in < "
#define TEXT230 "> at line "

#define TEXT240 "[No such screen]"
#define TEXT241 "%%Can't delete current screen"
#define TEXT242 "Find Screen: "
#define TEXT243 "Delete Screen: "
#define TEXT244 "%%No such function as '%s'"
#define TEXT245 "%%Division by Zero is illegal"
#define TEXT246 "%%Need function key number"
#define TEXT247 "%%Function key number out of range"
#define	TEXT248 "Enter Label String: "

/* some of these are just used in the microsoft windows version */
#define	TEXT300 "[Incorrect menu]"
#define	TEXT301 "[Too many nested popup menus]"
#define	TEXT302 "[Lack of resources]"
#define	TEXT303 "Menu: "
#define	TEXT304 "Function: "
#define	TEXT305 "Macro: "
#define	TEXT306 "Menu: "
#define	TEXT307 "Help file: "
#define	TEXT308 "Help key: "
#define TEXT310 "Alt+"
#define TEXT311 "Shift+"
#define TEXT312 "BkSp"
#define TEXT313 "Tab"
#define TEXT314 "Enter"
#define TEXT315 "Esc"
#define TEXT316 "Ctrl+"
#define TEXT317 "Home"
#define TEXT318 "DownArrow"
#define TEXT319 "UpArrow"
#define TEXT320 "LeftArrow"
#define TEXT321 "RightArrow"
#define TEXT322 "End"
#define TEXT323 "PageUp"
#define TEXT324 "PageDown"
#define TEXT325 "Ins"
#define TEXT326 "Del"
#define TEXT327 "F10"
#define CHAR328 'F'
#define TEXT329 "SpaceBar"
#define TEXT330 " - Message history"
#define TEXT331 "Global modes"
#define TEXT332 "Modes for buffer: "
#define TEXT333 "File write in progress. Quit later!"
#define TEXT334 "[No such directory]"
#define TEXT335 "Change screen name to: "
#define TEXT336 "[Screen name already in use]"
#define TEXT337 "cannot monitor external program"

